# Default values for iris-blue-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1



appText: "default  blue text"

httpproxy:
  fqdn: iris-blue-app.fluxtmc.aws.warroyo.com
